### ISSUE TITLE
v1.1.3 Alpha Task List

### ISSUE THREAD

**Issue by TheHeadmaster** [TheHeadmaster/XVTwiddle#3]
- [x] Bump readme to latest commit badge version
- [x] Create new branch
- [x] Bump assembly version
- [x] Bump Gitmoji changelog version
- [x] Open pull request
- [ ] Implement issue fixes
- [ ] Implement planned features
- [ ] Conduct testing
- [ ] Cleanup changelog
- [ ] Final changelog commit
- [ ] Add changelog items to pull request
- [ ] Ensure passing checks
- [ ] Merge pull request
- [ ] Close branch
- [ ] Close milestone
- [ ] Create new release tag
- [ ] Add changelog items to new release tag
- [ ] Upload installer to new release
- [ ] Create embed link to new release on Discord
